# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tolerance_svd <- function(m, tol, k) {
    .Call('_SlimPosition_tolerance_svd', PACKAGE = 'SlimPosition', m, tol, k)
}

matrix_power <- function(m, power, tol, k) {
    .Call('_SlimPosition_matrix_power', PACKAGE = 'SlimPosition', m, power, tol, k)
}

matrix_powers <- function(m, powers, tol, k) {
    .Call('_SlimPosition_matrix_powers', PACKAGE = 'SlimPosition', m, powers, tol, k)
}

gsvd_eig <- function(data, left_weights, right_weights, tol, nv, k) {
    .Call('_SlimPosition_gsvd_eig', PACKAGE = 'SlimPosition', data, left_weights, right_weights, tol, nv, k)
}

